Use the default text editor for viewing hosts file
ScriptTiger/Unified-Hosts-AutoUpdate pull request #13
Opened 2018-07-07 13:25 UTC by agyild

It could be also further improved with a fallback option (e.g. notepad.exe). But from my testing as long as .txt file ftype associations are correctly set and they use the `foo.exe %1` scheme, it should work correctly. I had to use an extra for loop because for example in the case of notepad.exe there are environment variables such as `%SystemRoot%` in the executable path which needs double-expansion, otherwise cmd sees % symbols as literal.

2018-07-07 14:14 UTC, ScriptTiger requested changes
Very nice! And I agree with your idea to add a fallback:

```
for /f "tokens=* usebackq" %%a in (`echo "!CMDVIEWTEXT:%%1=%HOSTS%!"`) do (start "" %%~a || start notepad %HOSTS%)
```

2018-07-07 14:21 UTC, agyild commented
Done, added the fallback.

2018-07-07 14:22 UTC, ScriptTiger approved these changes

2018-07-07 14:23 UTC, merged

2020-02-07 01:35 UTC, bonuswerte commented
How to do it

2020-02-07 02:01 UTC, ScriptTiger commented
@bonuswerte, is your hosts file not able to open from your default text editor? If you are having an issue, can you please open a new issue and copy and paste your console there?